version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: k9_care
    ports:
      - "54320:5432"
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=password --list"
      timeout: 10s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  etl:
    platform: linux/amd64
    depends_on:
        - postgres
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - ENV=$ENV
      - DB_URI=$DB_URI

volumes:
  db:
